<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elysia.Core.Application\Elysia.Core.Application.csproj" />
    <ProjectReference Include="..\Elysia.Core.Domain\Elysia.Core.Domain.csproj" />
    <ProjectReference Include="..\Elysia.Infraestructure.persistences\Elysia.Infraestructure.persistences.csproj" />
  </ItemGroup>

</Project>
